### ISSUE TITLE
使用自己的reid模型，测试报错

### ISSUE THREAD

**Issue by circlety** [songwsx/person_search_demo#26]
作者您好，我使用自己在 [reid-strong-baseline](https://github.com/michuanhaohao/reid-strong-baseline) 训练得到的模型，运行search.py时报错，报错信息：
Traceback (most recent call last):

  File "E:\person_search_demo\search.py", line 228, in <module>
    output=opt.output)

  File "E:\person_search_demo\search.py", line 38, in detect
    reidModel.load_param(reidCfg.TEST.WEIGHT)

  File "E:\person_search_demo\reid\modeling\baseline.py", line 63, in load_param
    param_dict = torch.load(trained_path)

  File "d:\anaconda3\envs\torch\lib\site-packages\torch\serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)

  File "d:\anaconda3\envs\torch\lib\site-packages\torch\serialization.py", line 574, in _load
    result = unpickler.load()

**ModuleNotFoundError: No module named 'modeling'**
请问可以提供一些解决的建议吗？

**Comment by sgg22** [comment]
同样的问题

**Comment by xiaoxinchudian** [comment]
一样，请问解决了嘛
